name: Build Lime3DS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Lime3DS for Windows
      run: |
        mkdir -p build
        cd build
        cmake -G "Visual Studio 16 2019" ..
        cmake --build . --config Release

    - name: Build Lime3DS for MacOS
      run: |
        mkdir -p build
        cd build
        cmake -G "Xcode" ..
        cmake --build . --config Release

    - name: Build Lime3DS for Android
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ..
        cmake --build . --config Release

    - name: Upload Lime3DS artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lime3ds
        path: build/

  switch-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up DevkitPro
      run: |
        sudo apt-get update
        sudo apt-get install -y devkitpro-pacman
        sudo dkp-pacman -S switch-dev

    - name: Build Nintendo Switch Homebrew
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=$DEVKITPRO/devkitARM
        export PATH=$PATH:$DEVKITARM/bin
        make -f Makefile.switch ARCH=arm64

    - name: Upload Nintendo Switch Homebrew artifact
      uses: actions/upload-artifact@v2
      with:
        name: lime3ds-switch
        path: build/lime3ds.nro
