name: Build Lime3DS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Lime3DS
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Upload Lime3DS artifact
      uses: actions/upload-artifact@v2
      with:
        name: lime3ds
        path: build/lime3ds

  switch-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up DevkitPro
      run: |
        sudo apt-get update
        sudo apt-get install -y devkitpro-pacman
        sudo dkp-pacman -S switch-dev

    - name: Build Nintendo Switch Homebrew
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=$DEVKITPRO/devkitARM
        export PATH=$PATH:$DEVKITARM/bin
        make -f Makefile.switch

    - name: Upload Nintendo Switch Homebrew artifact
      uses: actions/upload-artifact@v2
      with:
        name: lime3ds-switch
        path: build/lime3ds.nro
